export default [
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
        },
        href: "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
        id: "1uNFoZAHBGtllmzznpCI3s",
        name: "Justin Bieber",
        type: "artist",
        uri: "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1anyVhU62p31KFi8MEzkbf"
        },
        href: "https://api.spotify.com/v1/artists/1anyVhU62p31KFi8MEzkbf",
        id: "1anyVhU62p31KFi8MEzkbf",
        name: "Chance the Rapper",
        type: "artist",
        uri: "spotify:artist:1anyVhU62p31KFi8MEzkbf"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/4hR7jjsPvRwwcHx8ntJSQS"
    },
    href: "https://api.spotify.com/v1/albums/4hR7jjsPvRwwcHx8ntJSQS",
    id: "4hR7jjsPvRwwcHx8ntJSQS",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273572c68f79b356c21202e248c",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02572c68f79b356c21202e248c",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851572c68f79b356c21202e248c",
        width: 64
      }
    ],
    name: "Holy",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:4hR7jjsPvRwwcHx8ntJSQS"
  },
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7FNnA9vBm6EKceENgCGRMb"
        },
        href: "https://api.spotify.com/v1/artists/7FNnA9vBm6EKceENgCGRMb",
        id: "7FNnA9vBm6EKceENgCGRMb",
        name: "Anitta",
        type: "artist",
        uri: "spotify:artist:7FNnA9vBm6EKceENgCGRMb"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7iK8PXO48WeuP03g8YR51W"
        },
        href: "https://api.spotify.com/v1/artists/7iK8PXO48WeuP03g8YR51W",
        id: "7iK8PXO48WeuP03g8YR51W",
        name: "Myke Towers",
        type: "artist",
        uri: "spotify:artist:7iK8PXO48WeuP03g8YR51W"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/5J7bWCachL4Q662xAfzyJd"
    },
    href: "https://api.spotify.com/v1/albums/5J7bWCachL4Q662xAfzyJd",
    id: "5J7bWCachL4Q662xAfzyJd",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273774b6059847afd5681899dde",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02774b6059847afd5681899dde",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851774b6059847afd5681899dde",
        width: 64
      }
    ],
    name: "Me Gusta (with Cardi B & Myke Towers)",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:5J7bWCachL4Q662xAfzyJd"
  },
  {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3DiDSECUqqY1AuBP8qtaIa"
        },
        href: "https://api.spotify.com/v1/artists/3DiDSECUqqY1AuBP8qtaIa",
        id: "3DiDSECUqqY1AuBP8qtaIa",
        name: "Alicia Keys",
        type: "artist",
        uri: "spotify:artist:3DiDSECUqqY1AuBP8qtaIa"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/1vTV3bbycMPkbIocAma0eN"
    },
    href: "https://api.spotify.com/v1/albums/1vTV3bbycMPkbIocAma0eN",
    id: "1vTV3bbycMPkbIocAma0eN",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273d6fb232eb97b58b0beff9b05",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02d6fb232eb97b58b0beff9b05",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851d6fb232eb97b58b0beff9b05",
        width: 64
      }
    ],
    name: "ALICIA",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 15,
    type: "album",
    uri: "spotify:album:1vTV3bbycMPkbIocAma0eN"
  },
  {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0u2FHSq3ln94y5Q57xazwf"
        },
        href: "https://api.spotify.com/v1/artists/0u2FHSq3ln94y5Q57xazwf",
        id: "0u2FHSq3ln94y5Q57xazwf",
        name: "Keith Urban",
        type: "artist",
        uri: "spotify:artist:0u2FHSq3ln94y5Q57xazwf"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/4F3rUFQcKJm6b1BsJRwAbf"
    },
    href: "https://api.spotify.com/v1/albums/4F3rUFQcKJm6b1BsJRwAbf",
    id: "4F3rUFQcKJm6b1BsJRwAbf",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b27320e1f9d26567e0fbb562a6a5",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e0220e1f9d26567e0fbb562a6a5",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d0000485120e1f9d26567e0fbb562a6a5",
        width: 64
      }
    ],
    name: "THE SPEED OF NOW Part 1",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 16,
    type: "album",
    uri: "spotify:album:4F3rUFQcKJm6b1BsJRwAbf"
  },
  {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/4npEfmQ6YuiwW1GpUmaq3F"
        },
        href: "https://api.spotify.com/v1/artists/4npEfmQ6YuiwW1GpUmaq3F",
        id: "4npEfmQ6YuiwW1GpUmaq3F",
        name: "Ava Max",
        type: "artist",
        uri: "spotify:artist:4npEfmQ6YuiwW1GpUmaq3F"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/6B1U2tJse7tS9Yi4VJjZAA"
    },
    href: "https://api.spotify.com/v1/albums/6B1U2tJse7tS9Yi4VJjZAA",
    id: "6B1U2tJse7tS9Yi4VJjZAA",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2732ca6f6a1cf2cb7c43de08db5",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e022ca6f6a1cf2cb7c43de08db5",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048512ca6f6a1cf2cb7c43de08db5",
        width: 64
      }
    ],
    name: "Heaven & Hell",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 15,
    type: "album",
    uri: "spotify:album:6B1U2tJse7tS9Yi4VJjZAA"
  },
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3kf0gOpxWtkyeMNJVDQPtd"
        },
        href: "https://api.spotify.com/v1/artists/3kf0gOpxWtkyeMNJVDQPtd",
        id: "3kf0gOpxWtkyeMNJVDQPtd",
        name: "Smoke DZA",
        type: "artist",
        uri: "spotify:artist:3kf0gOpxWtkyeMNJVDQPtd"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop"
        },
        href: "https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop",
        id: "137W8MRPWKqSmrBGDBFSop",
        name: "Wiz Khalifa",
        type: "artist",
        uri: "spotify:artist:137W8MRPWKqSmrBGDBFSop"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6X8WdFjrNhXATMDSs26aCc"
        },
        href: "https://api.spotify.com/v1/artists/6X8WdFjrNhXATMDSs26aCc",
        id: "6X8WdFjrNhXATMDSs26aCc",
        name: "Curren$y",
        type: "artist",
        uri: "spotify:artist:6X8WdFjrNhXATMDSs26aCc"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/2LAIzdrNAa8cHandGdqjL6"
    },
    href: "https://api.spotify.com/v1/albums/2LAIzdrNAa8cHandGdqjL6",
    id: "2LAIzdrNAa8cHandGdqjL6",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273c660eaf8f259768210c3880c",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02c660eaf8f259768210c3880c",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851c660eaf8f259768210c3880c",
        width: 64
      }
    ],
    name: "Santos Party House",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 2,
    type: "album",
    uri: "spotify:album:2LAIzdrNAa8cHandGdqjL6"
  },
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI"
        },
        href: "https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI",
        id: "2wY79sveU1sp5g7SokKOiI",
        name: "Sam Smith",
        type: "artist",
        uri: "spotify:artist:2wY79sveU1sp5g7SokKOiI"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/2IAyprsfyoPBGDvbLjgsN5"
    },
    href: "https://api.spotify.com/v1/albums/2IAyprsfyoPBGDvbLjgsN5",
    id: "2IAyprsfyoPBGDvbLjgsN5",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273f207514228c0a5db1ae3b116",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02f207514228c0a5db1ae3b116",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851f207514228c0a5db1ae3b116",
        width: 64
      }
    ],
    name: "Diamonds",
    release_date: "2020-09-17",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:2IAyprsfyoPBGDvbLjgsN5"
  },
  {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/4Ga1P7PMIsmqEZqhYZQgDo"
        },
        href: "https://api.spotify.com/v1/artists/4Ga1P7PMIsmqEZqhYZQgDo",
        id: "4Ga1P7PMIsmqEZqhYZQgDo",
        name: "Lil Tecca",
        type: "artist",
        uri: "spotify:artist:4Ga1P7PMIsmqEZqhYZQgDo"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/389zGArsMlwuPorS4Cw7IX"
    },
    href: "https://api.spotify.com/v1/albums/389zGArsMlwuPorS4Cw7IX",
    id: "389zGArsMlwuPorS4Cw7IX",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2732026d0048432d395f6f715b5",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e022026d0048432d395f6f715b5",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048512026d0048432d395f6f715b5",
        width: 64
      }
    ],
    name: "Virgo World",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 19,
    type: "album",
    uri: "spotify:album:389zGArsMlwuPorS4Cw7IX"
  },
  {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6sHCvZe1PHrOAuYlwTLNH4"
        },
        href: "https://api.spotify.com/v1/artists/6sHCvZe1PHrOAuYlwTLNH4",
        id: "6sHCvZe1PHrOAuYlwTLNH4",
        name: "Gus Dapperton",
        type: "artist",
        uri: "spotify:artist:6sHCvZe1PHrOAuYlwTLNH4"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/1D8cnABQfjvfQC2Cdk889m"
    },
    href: "https://api.spotify.com/v1/albums/1D8cnABQfjvfQC2Cdk889m",
    id: "1D8cnABQfjvfQC2Cdk889m",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2731dc1bd83254e89b474ca496b",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e021dc1bd83254e89b474ca496b",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048511dc1bd83254e89b474ca496b",
        width: 64
      }
    ],
    name: "Orca",
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 10,
    type: "album",
    uri: "spotify:album:1D8cnABQfjvfQC2Cdk889m"
  }
];
