/*
 * The first index [0] has an audio preview on its tracks list
 * The second index [1] don't have audio preview on its tracks list
 */
export default [
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3eqjTLE0HfPfh78zjh6TqT"
        },
        href: "https://api.spotify.com/v1/artists/3eqjTLE0HfPfh78zjh6TqT",
        id: "3eqjTLE0HfPfh78zjh6TqT",
        name: "Bruce Springsteen",
        type: "artist",
        uri: "spotify:artist:3eqjTLE0HfPfh78zjh6TqT"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    copyrights: [{ text: "(P) 2020 Bruce Springsteen", type: "P" }],
    external_ids: { upc: "886448725930" },
    external_urls: {
      spotify: "https://open.spotify.com/album/3KTfabkxxVzhXupBScd2sK"
    },
    genres: [],
    href: "https://api.spotify.com/v1/albums/3KTfabkxxVzhXupBScd2sK",
    id: "3KTfabkxxVzhXupBScd2sK",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b27381faf2785a4d017b963e5620",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e0281faf2785a4d017b963e5620",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d0000485181faf2785a4d017b963e5620",
        width: 64
      }
    ],
    label: "Columbia",
    name: "Letter To You",
    popularity: 61,
    release_date: "2020-09-10",
    release_date_precision: "day",
    total_tracks: 1,
    tracks: {
      href:
        "https://api.spotify.com/v1/albums/3KTfabkxxVzhXupBScd2sK/tracks?offset=0&limit=50",
      items: [
        {
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3eqjTLE0HfPfh78zjh6TqT"
              },
              href: "https://api.spotify.com/v1/artists/3eqjTLE0HfPfh78zjh6TqT",
              id: "3eqjTLE0HfPfh78zjh6TqT",
              name: "Bruce Springsteen",
              type: "artist",
              uri: "spotify:artist:3eqjTLE0HfPfh78zjh6TqT"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 295493,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/3fXP54Fi7oftEe9wIZq2dq"
          },
          href: "https://api.spotify.com/v1/tracks/3fXP54Fi7oftEe9wIZq2dq",
          id: "3fXP54Fi7oftEe9wIZq2dq",
          is_local: false,
          name: "Letter To You",
          preview_url:
            "https://p.scdn.co/mp3-preview/3639db8352e65bc94df187e085fa96e2e43fdea8?cid=0d9dd562e9394e88a4212d8d131be672",
          track_number: 1,
          type: "track",
          uri: "spotify:track:3fXP54Fi7oftEe9wIZq2dq"
        }
      ],
      limit: 50,
      next: null,
      offset: 0,
      previous: null,
      total: 1
    },
    type: "album",
    uri: "spotify:album:3KTfabkxxVzhXupBScd2sK"
  },
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
        },
        href: "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
        id: "1uNFoZAHBGtllmzznpCI3s",
        name: "Justin Bieber",
        type: "artist",
        uri: "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1anyVhU62p31KFi8MEzkbf"
        },
        href: "https://api.spotify.com/v1/artists/1anyVhU62p31KFi8MEzkbf",
        id: "1anyVhU62p31KFi8MEzkbf",
        name: "Chance the Rapper",
        type: "artist",
        uri: "spotify:artist:1anyVhU62p31KFi8MEzkbf"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    copyrights: [
      { text: "© 2020 The Island Def Jam Music Group", type: "C" },
      {
        text: "℗ 2020 Def Jam Recordings, a division of UMG Recordings, Inc.",
        type: "P"
      }
    ],
    external_ids: { upc: "00602435179001" },
    external_urls: {
      spotify: "https://open.spotify.com/album/4hR7jjsPvRwwcHx8ntJSQS"
    },
    genres: [],
    href: "https://api.spotify.com/v1/albums/4hR7jjsPvRwwcHx8ntJSQS",
    id: "4hR7jjsPvRwwcHx8ntJSQS",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273572c68f79b356c21202e248c",
        width: 640
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02572c68f79b356c21202e248c",
        width: 300
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851572c68f79b356c21202e248c",
        width: 64
      }
    ],
    label: "RBMG/Def Jam",
    name: "Holy",
    popularity: 81,
    release_date: "2020-09-18",
    release_date_precision: "day",
    total_tracks: 1,
    tracks: {
      href:
        "https://api.spotify.com/v1/albums/4hR7jjsPvRwwcHx8ntJSQS/tracks?offset=0&limit=50",
      items: [
        {
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s"
              },
              href: "https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s",
              id: "1uNFoZAHBGtllmzznpCI3s",
              name: "Justin Bieber",
              type: "artist",
              uri: "spotify:artist:1uNFoZAHBGtllmzznpCI3s"
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1anyVhU62p31KFi8MEzkbf"
              },
              href: "https://api.spotify.com/v1/artists/1anyVhU62p31KFi8MEzkbf",
              id: "1anyVhU62p31KFi8MEzkbf",
              name: "Chance the Rapper",
              type: "artist",
              uri: "spotify:artist:1anyVhU62p31KFi8MEzkbf"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 212093,
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/track/5u1n1kITHCxxp8twBcZxWy"
          },
          href: "https://api.spotify.com/v1/tracks/5u1n1kITHCxxp8twBcZxWy",
          id: "5u1n1kITHCxxp8twBcZxWy",
          is_local: false,
          name: "Holy (feat. Chance The Rapper)",
          preview_url: null,
          track_number: 1,
          type: "track",
          uri: "spotify:track:5u1n1kITHCxxp8twBcZxWy"
        }
      ],
      limit: 50,
      next: null,
      offset: 0,
      previous: null,
      total: 1
    },
    type: "album",
    uri: "spotify:album:4hR7jjsPvRwwcHx8ntJSQS"
  }
];
